### ISSUE TITLE
puppet-cleaner incompatible with Puppet 3.x

### ISSUE THREAD

**Issue by joschi** [santana/puppet-cleaner#2]
puppet-clean currently doesn't work with Puppet 3.x:

```
# puppet-clean 
/usr/lib/ruby/gems/2.0.0/gems/puppet-3.1.1/lib/puppet/parser.rb:2:in `<top (required)>': uninitialized constant Puppet (NameError)
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /usr/lib/ruby/gems/2.0.0/gems/puppet-cleaner-0.1.0/lib/puppet-cleaner.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/lib/ruby/gems/2.0.0/gems/puppet-cleaner-0.1.0/bin/puppet-clean:4:in `<top (required)>'
        from /usr/bin/puppet-clean:23:in `load'
        from /usr/bin/puppet-clean:23:in `<main>'
```

It would be great if puppet-clean could be used with newer versions of Puppet.

**Comment by santana** [comment]
Hi joschi,

thanks for trying it out and report it back. The incompatibility with Puppet 3.x is expected, since puppet-cleaner heavily depends on puppet's implementation details, which may have changed from version 2.7.11 to 3.x.

If there's enough interest on puppet 3.x support I can work on it.

**Comment by mestachs** [comment]
@santana you can take a look at http://bombasticmonkey.com/2013/01/28/fix-simple-problems-with-puppet-lint/

**Comment by drewblessing** [comment]
How might a person express interest in puppet 3 support? :)

**Comment by santana** [comment]
you have just did :)

Let me dive into puppet 3 lexer to see how can be tweaked.

**Comment by blalor** [comment]
I would also be interested in puppet 3 support. :-)

**Comment by santana** [comment]
ok! :) Let's reopen this ticket.

**Comment by santana** [comment]
@joschi @drewblessing @blalor , I've just uploaded a fix to branch p3. puppet-cleaner is now working with puppet 3.1 and passed my tests.

Would you help me test it as well?

Just download the branch and run:

```
gem build puppet-cleaner.gemspec
sudo gem install --local puppet-cleaner-0.2.0.gem
```

Thanks in advance.

**Comment by santana** [comment]
I ran even more tests and it runs fine so far. I've publishing it today.
