### ISSUE TITLE
parser load error with puppet 2.7.20

### ISSUE THREAD

**Issue by logicminds** [santana/puppet-cleaner#3]
Doesn't seem to work with puppet 2.7.20
# puppet-clean -h

/Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/parser/type_loader.rb:4: uninitialized constant Puppet::Parser (NameError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/resource/type_collection.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/resource/type_collection_helper.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/resource.rb:16
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet.rb:119
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/parser/parser.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-2.7.20/lib/puppet/parser.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-cleaner-0.1.0/lib/puppet-cleaner.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/puppet-cleaner-0.1.0/bin/puppet-clean:4
    from /usr/bin/puppet-clean:23:in `load'
    from /usr/bin/puppet-clean:23

**Comment by santana** [comment]
Hi logicminds,

I have reviewed the whole chain of requires and can't find anything wrong. Even puppet and parser include themselves at least twice.

Do you know of any modifications to your local puppet installation?

Try this in irb:

require 'puppet/parser'
Puppet::Parser

it should return

=> Puppet::Parser

if it does not, try this:

require 'puppet'
Puppet::Parser

and this time it must return the above. Otherwise, something may be wrong with the puppet installation.

Thanks in advance for your feedback!

**Comment by santana** [comment]
In any case, the recent fix for puppet 3.1 would fix this
