### ISSUE TITLE
Change double to single quotes if there are no variables

### ISSUE THREAD

**Issue by nikolavp** [santana/puppet-cleaner#7]
I am not sure If this is in the style guide but I find it useful and know that puppet-lint is giving a warning on it.

If there is a string value that doesn't contain variable interpolation, the quotes should be transformed from double to single quotes.
## 

Nikola

**Comment by santana** [comment]
Hi @nikolavp

puppet-cleaner fixes that by default; it even considers if there are not special characters like \r \t and \n

**Comment by matthewbarr** [comment]
Just be careful of password hashes.  There was an issue w/ puppet lint picking it up wrong, since it needed to be single quotes, even though there was a $ inside the value.

**Comment by santana** [comment]
Thanks @matthewbarr for the heads up.

There lies the beauty of reusing puppet's own parser. puppet-cleaner sees what the compiler sees. So, it's a non-issue for puppet-cleaner.
