### ISSUE TITLE
Still not working with puppet 3.1 and puppet 2.7.2X

### ISSUE THREAD

**Issue by deniszh** [santana/puppet-cleaner#8]
Working fine with 2.7.11, but puppet-diff do not work with e.g. puppet-2.7.21:

dzhdanov@deniszh:~/git/ecg-puppet$ puppet-diff
/var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/parser/type_loader.rb:4: uninitialized constant Puppet::Parser (NameError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/resource/type_collection.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/resource/type_collection_helper.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/resource.rb:16
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet.rb:119
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/parser/parser.rb:9
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-2.7.21/lib/puppet/parser.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/lib/puppet-cleaner/inspect.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/bin/puppet-diff:3
    from /usr/local/bin/puppet-diff:19:in `load'
    from /usr/local/bin/puppet-diff:19

puppet-diff and puppet-inspect also do not works with puppet 3.1.1:

dzhdanov@deniszh:~/git/ecg-puppet$ puppet-diff
/var/lib/gems/1.8/gems/puppet-3.1.1/lib/puppet/parser.rb:2: uninitialized constant Puppet (NameError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/lib/puppet-cleaner/inspect.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/bin/puppet-diff:3
    from /usr/local/bin/puppet-diff:19:in `load'
    from /usr/local/bin/puppet-diff:19
dzhdanov@deniszh:~/git/ecg-puppet$ puppet-inspect 
/var/lib/gems/1.8/gems/puppet-3.1.1/lib/puppet/parser.rb:2: uninitialized constant Puppet (NameError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/lib/puppet-cleaner/inspect.rb:1
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/puppet-cleaner-0.2.0/bin/puppet-inspect:3
    from /usr/local/bin/puppet-inspect:19:in`load'
    from /usr/local/bin/puppet-inspect:19

**Comment by santana** [comment]
Thanks @deniszh for the report. It's a mistake from my part. It's now fixed in 0.2.1

**Comment by deniszh** [comment]
Hi Gerardo,

Thanks for quick response!
Keeping digging with puppet-cleaner more... :)

2013/5/3 Gerardo Santana notifications@github.com
