### ISSUE TITLE
Cosmetics with '####' comment lines

### ISSUE THREAD

**Issue by alexjurkiewicz** [santana/puppet-cleaner#9]
Puppet-clean proposes changes like this:

```
-    ########################################################
+    # #######################################################
```

I think it should special case lines consisting of only # symbols and leave them alone.

Thanks for the tool!

**Comment by santana** [comment]
Hi @alexjurkiewicz 

thanks for the report. It's fixed now in master.

**Comment by alexjurkiewicz** [comment]
Great! Thanks for the tool :)
